---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe
    opendatahub.io/template-name: vllm-runtime
    openshift.io/display-name: {{ .Values.mainLLM.name }}
  name: {{ .Values.mainLLM.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{`{{.Name}}`}}'
        {{- if .Values.mainLLM.enableAutoToolChoice }}
        - '--enable-auto-tool-choice'
        {{- end }}
        {{- if .Values.mainLLM.enableChunkedPrefill }}
        - '--enable-chunked-prefill'
        {{- end }}
        {{- if .Values.mainLLM.toolCallParser }}
        - '--tool-call-parser'
        - {{ .Values.mainLLM.toolCallParser }}
        {{- end }}
        {{- if .Values.mainLLM.chatTemplate }}
        - '--chat-template'
        - {{ .Values.mainLLM.chatTemplate }}
        {{- end }}
        {{- if .Values.mainLLM.maxModelLen }}
        - '--max-model-len'
        - {{ .Values.mainLLM.maxModelLen | quote }}
        {{- end }}
        {{- if .Values.mainLLM.maxNumSeqs }}
        - '--max-num-seqs'
        - {{ .Values.mainLLM.maxNumSeqs | quote }}
        {{- end }}
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: {{ .Values.mainLLM.image | default "quay.io/modh/vllm@sha256:0d55419f3d168fd80868a36ac89815dded9e063937a8409b7edf3529771383f3" }}
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  {{- if .Values.mainLLM.tolerations }}
  tolerations:
    {{- toYaml .Values.mainLLM.tolerations | nindent 4 }}
  {{- end }}
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm